### ISSUE TITLE
mu-plugins caveats

### ISSUE THREAD

**Issue by sandrodz** [wordplate/autoloader#8]
WP mu-plugins have some serious drawbacks. E.g. activation hooks are not run, and a lot of plugins depend on it to setup db and run other scripts.

https://codex.wordpress.org/Must_Use_Plugins

> Despite its suitability for many special cases, the mu-plugins system is not always ideal and has several downsides that make it innapropriate in certain circumstances. Below are several important caveats to keep in mind:

> (html)Plugins in the must-use directory will not appear in the update notifications nor show their update status on the plugins page, so you are responsible for learning about and performing updates on your own.
> 
> Activation hooks are not executed in plugins added to the must-use plugins folder. These hooks are used by many plugins to run installation code that sets up the plugin initially and/or uninstall code that cleans up when the plugin is deleted. Plugins depending on these hooks may not function in the mu-plugins folder, and as such all plugins should be carefully tested specifically in the mu-plugins directory before being deployed to a live site.
> 
> WordPress only looks for PHP files right inside the mu-plugins directory, and (unlike for normal plugins) not for files in subdirectories. You may want to create a proxy PHP loader file inside the mu-plugins director:

Does` wordplate/autoloader` deal with these issues in any way?

**Comment by tditlu** [comment]
We have been working hard to get `wordplate/autoloader` to mimic activation hooks and to work just like if the plugin is placed in the _plugins_ folder.
The things it won't do is to run the `plugin delete` hook, because the only way to delete a plugin is to delete the plugin director and then the code for the `plugin delete_` hook is also gone.
There is also no notification/update button for plugins, so plugins have to be updated through `composer update`.
